version: "3"
services:
  bitcoin-core-regtest:
    container_name: bitcoin-core-regtest
    image: ruimarinho/bitcoin-core:0.21.1
    command: -printtoconsole
      -txindex=1
      -server=1
      -regtest=1
    environment:
      - BITCOIN_DATA=/data
    volumes:
      - ${DATA_VOL}:/data
    networks:
      - bitcoin-network
  #    ports:
  #      - "8332:8332"
  #      - "8333:8333"
  mongo:
    container_name: mongo
    image: mongo:4.0.27-xenial
    #    ports:
    #      - "27017:27017"
    volumes:
      - ${DB_VOL}:/data/db
    networks:
      - bitcoin-network
  ipfs:
    container_name: ipfs
    #this image doesn't work on ARM64 yet, use mhoekstra/go-ipfs:v0.7.0 if you want to deploy on ARM
    image: ipfs/go-ipfs
    environment:
      - IPFS_PATH=/data/ipfs
    volumes:
      - ${IPFS_VOL}:/data/ipfs
    networks:
      - bitcoin-network
    ports:
      #      - "5001:5001"
      - "4001:4001"
  #      - "8080:8080"

  ion-bitcoin-regtest:
    container_name: ion-bitcoin-regtest
    image: node:lts-alpine3.14
    command: "npm run bitcoin"
    working_dir: /ion
    environment:
      - ION_BITCOIN_CONFIG_FILE_PATH=/ion/json/regtest-bitcoin-docker-config.json
      - ION_BITCOIN_VERSIONING_CONFIG_FILE_PATH=/ion/json/regtest-bitcoin-versioning.json
    volumes:
      - ..:/ion
      - ${DATA_VOL}:/bitcoindata
    networks:
      - bitcoin-network
    ports:
      - "3002:3002"

  ion-core-regtest:
    container_name: ion-core-regtest
    image: node:lts-alpine3.14
    command: "npm run core"
    working_dir: /ion
    environment:
      - ION_CORE_CONFIG_FILE_PATH=/ion/json/regtest-core-docker-config.json
      - ION_CORE_VERSIONING_CONFIG_FILE_PATH=/ion/json/regtest-core-versioning.json
    volumes:
      - ..:/ion
    networks:
      - bitcoin-network
    ports:
      - "3000:3000"
networks:
  bitcoin-network:
    driver: bridge
